# Attempt to get a newer oraclejdk8..
# See https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

language: java

# If newer Oracle JDK is needed, uncomment:
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer    
# .. and comment out:
jdk:
  - openjdk8


cache:
  directories:
    - '$HOME/.m2/repository'

install: /bin/true

notifications:
  email:
    - notifications@commons.apache.org

after_success:
  - mvn -V --no-transfer-progress clean test coveralls:report
 
